# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 09:51
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link2', '0005_auto_20170323_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerlink2plugin',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Anchor ID'),
        ),
        migrations.AddField(
            model_name='filerlink2plugin',
            name='encrypt_mailto',
            field=models.BooleanField(default=False, help_text='Encrypt the mailto, as protection against bots collecting mails addresses.', verbose_name='Encryption of Mailto'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='mailto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='mailto'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='page_link',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='url',
            field=models.CharField(blank=True, help_text='The url must specify the protocol, e.g. https://DOMAIN.tld', max_length=2000, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='linkhealthstate',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkhealth', to='cmsplugin_filer_link2.FilerLink2Plugin', verbose_name='Link name'),
        ),
    ]
