# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-29 10:31
from __future__ import unicode_literals

import cmsplugin_filer_link2.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link2', '0006_anchor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=100, validators=[cmsplugin_filer_link2.validators.validate_anchor_id], verbose_name='Anchor ID'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='link_style',
            field=models.CharField(choices=[('default', 'Default'), ('button', 'Button'), ('ghost_button', 'Ghost Button')], default='default', max_length=255, verbose_name='link style'),
        ),
    ]
