# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 12:17
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link2', '0007_auto_20190129_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkhealthstate',
            name='state',
            field=models.CharField(choices=[('3xx', 'Redirected'), ('4xx', 'Not reachable'), ('5xx', 'Server error'), ('bad', 'Bad configured'), ('to', 'Timeout')], max_length=3, verbose_name='State'),
        ),
    ]