# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link2', '0008_timeout_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='url',
            field=models.URLField(blank=True, help_text='The url must specify the protocol, e.g. https://DOMAIN.tld', max_length=2000, null=True, verbose_name='url'),
        ),
    ]
