# Generated by Django 2.2.11 on 2020-03-24 21:50

import cmsplugin_filer_link2.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link2', '0009_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='encrypt_mailto',
            field=models.BooleanField(default=True, help_text='Encrypt the mailto, as protection against bots collecting mails addresses.', verbose_name='Encryption of Mailto'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='link_style',
            field=models.CharField(choices=[(' ', 'Default')], default=' ', max_length=255, verbose_name='link style'),
        ),
        migrations.AlterField(
            model_name='filerlink2plugin',
            name='page_link',
            field=cmsplugin_filer_link2.fields.Select2PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='page'),
        ),
    ]
